language: java

before_install:
  - ./gradlew wrapper --gradle-version=4.10 --distribution-type=bin

jdk:
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk-ea

script:
  - ./gradlew check --info

after_success:
- ./gradlew jacocoTestReport coveralls
