language: java
jdk:
  - oraclejdk9
  - openjdk9
  - oraclejdk10
  - openjdk10

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - "NBh2cdanT1LrZC2ZjnbL3F0/6gW9Dg094DpmV1O6AwWQcSKWG2k9LDGKdOnWnzu3DKtanLuMs6KSC3WdicKplibVm/1UAF/a56/w5Ya60Hd4keOWUonfrHbkRPMAUT6NPsuzMoqCeWK7PzfbQRAA65sOJ0mM1yrvAoDme61ucducXIT6hGrEv/6tCgN0Tu4HcVTeZVugHAnrMggytm74jVX5sW2pSwF/MR1d8DWR4SHOppCbDZmWSspOHu1Ozud0bdVSPFUUzBRFQeg1i05zW1LtBq1hfM6KFjQRmC6zLqNQUyS7Prj4MgNcxMBIq+uqsG5RnrxLqNCZ7J5lGm4+ycsvu8uYpyqdlYzIcotV4eu+PndBc3qf4On80sgoKsAqP9cFypfpE/w/i64eRlG9dvGqSQnYLFSjP9uDfoYjUUCaPkJqHVDN51PHKfDvsavOpjnrGZxCppTb6MLoYsNU2RNKgTjR6pX0kb4Y1mXKsuAL9uBf5rqK/CJdRiNtUzB4cJyPlQH5AqtKYutseDezkeX0gzVX/JzT1/LPgpcjexjKPqnQtaeIo+eXfB24ZsNxh9N++kXuwcb7WNFRRbif8EohheaevtONRO9JHYPhDs6PA6uUTe3xL3Plzrm9nwfyREFVs9dFk1PZrrz4dkTOo/Z3H5H5r4Dgb1OT4IJOFdg="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "artem-smotrakov/tlsbunny"
      description: "tlsbunny is a framework for building negative tests and fuzzers for TLS 1.3 implementations"
    notification_email: artem.smotrakov@gmail.com
    build_command_prepend: "./gradlew assemble"
    build_command: "./gradlew build"
    branch_pattern: coverity_scan
    
