sudo: required
language: java
dist: trusty

services:
  - docker

env:
  global:
    - OPENSSL_IMAGE=artemsmotrakov/tlsbunny_openssl_tls13:2019_04_02
    - WOLFSSL_IMAGE=artemsmotrakov/tlsbunny_wolfssl_tls13:2019_03_03
    - PICOTLS_IMAGE=artemsmotrakov/tlsbunny_picotls_tls13:2019_04_10
    - GNUTLS_IMAGE=artemsmotrakov/tlsbunny_gnutls_tls13:2019_04_13

before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  - ./gradlew wrapper --gradle-version 4.10.2
  - docker pull ${OPENSSL_IMAGE}
  - docker pull ${WOLFSSL_IMAGE}
  - docker pull ${PICOTLS_IMAGE}
  - docker pull ${GNUTLS_IMAGE}
  - docker run ${OPENSSL_IMAGE} /bin/bash -c "openssl version"
  - docker run ${WOLFSSL_IMAGE} /bin/bash -c "examples/server/server -h"
  - docker run ${PICOTLS_IMAGE} /bin/bash -c "/var/src/picotls/cli -h"
  - docker run ${GNUTLS_IMAGE}  /bin/bash -c "gnutls-serv -h"

matrix:
  include:
    - env: JDK='OpenJDK 11'
      install: . ./install-jdk.sh -F 11 -L GPL
    - env: JDK='OpenJDK 12'
      install: . ./install-jdk.sh -F 12 -L GPL

script:
  - ./scripts/build_and_test.sh

addons:
  sonarcloud:
    organization: "artem-smotrakov-github"
    token:
      secure: >
        dluei+0gd66JePCjVlPagI8hrZ56BU5CaQV3SLzskTe2iHyV/Xvspwn5FN4c3lwKtLbr0pQX
        pbpddKEinqpZ9JUFgvtpl1MoI6fI61vrtBgrZTsAPvWgQYN7OluvKSjaIK6Q4SJAd6KLS1GB
        GEG55np4rD3W4fKW1jyz+ZaAOvQHxBT5JkOARRZKtLHgL8iN6I8YYF7WGwwp5BtrfALz5jTP
        KsIcuWXqICLwVmZmnGjWnsqRxZuYxcWX27jcoWuGg8ei+BjUf9yWzevkqVU3896vg/sCWjua
        +jJzVXXElmrXe3bJXGd0zS8LyjvrSVFwueY4pMy1HYZwtBDJMb2lriDTimeVmb+Bb2YJDfUu
        q5f2w20Cp/RbWvvCMoYVerosSk3OaqYLPEHFFu+MSI76erHgHDHJX+i9A1MwU0nl7JCivejp
        qMpho52dGUScqAfWeXE68Kd5/1nKNQr+roMhzyQnFwFTJahD3BVmxXmhcLR4sYT0inqxSGQ+
        leAfYS0qLztz/2QthZyGvzPhiP/orzhBK2AUnSQjPu3hX2azkH1Pjgm/pW2twdkkURNstQvL
        j+PboFJZzJjMrmgJ6q00dclKEvHU3hx69ea//9b0l7+wPJnhN17fsTfc84ATpXadtB2K6nCr
        abGnlxoK0V5RO7MdeYzdMCdsQCqTLry/BbY=
