language: java
jdk:
  - oraclejdk9
  - openjdk9
  - oraclejdk10
  - openjdk10

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "rojjvX/mYInhWLhwms91Fx8FG1Zo+iTGtUerfhGJgUEoE07cVcen1m5cEYb0rPt8HSql4jif/FN8AFmsB62Xj2/IMcnSurvEoEdPHTDCjqZW/CwIsxqfkBj6bovlPbPzPto4iWhXH7VjFxEQBWlmopUjB//O6Mk11ib/YYesf11kAuSNYk8dk4xOs5sXKtl+a2gX4E2xzsFdBAUzYY5g8XsK01/5q6dE/7UYFzn+cYwl8251gdT43q4k9d5Nx/ZpWQcg1eH4bKwN8vNQJzL0g6uTXRMgyENxc4ef3vesUu1u9rqrZqOq8KCJFHWxGlpK/GBO27ZBpVK/SGX22WYS13XUegyZdFapBlT+2vKCDsS34qNTA1YtClVWvLV47cyqxLFJZ9KsEA+qmhcpdz1675Lmv0pFVhpXBaQOE7AdS6cIkqMYiaQCSj803ge9yGluMLbv6uZyYKQdDVjf851ziArMHk45gdrE2jD/1lQOqwfzAIgiWWjtz/NbUjzoVQkzd8vNs6/xT8ZOORSqrDnQBj3bzhDuX+n6eZ1PgHMPS1nDkUvmPz3UecJf4mLP58zljnsmsWIUYBViJ2WqRCOht0FvdEmAtf6VzZmcQAboiQlbgXrWgbNfIWRrPsjcxrFKdkQSaeHCzQ7rtTThi2IhE4HQBCxCyT+DSjSTWdp8XME="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "artem-smotrakov/tlsbunny"
      description: "tlsbunny is a framework for building negative tests and fuzzers for TLS 1.3 implementations"
    notification_email: artem.smotrakov@gmail.com
    build_command_prepend: "./gradlew assemble"
    build_command: "./gradlew build"
    branch_pattern: coverity_scan
    
